server:
  port: 8011
spring:
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
signing:
  key: "345345fsdfsf5345"
