version: '3'
services:
  rabbitmq:
    image: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitbus
      - RABBITMQ_DEFAULT_PASS=TbFpVQzneY2j
    networks:
      cloud:
        ipv4_address: 192.168.0.14

  configuration:
    image: cloud/configuration
    restart: always
    environment:
      - RABBITMQ_HOST=192.168.0.14
      - RABBITMQ_USERNAME=rabbitbus
      - RABBITMQ_PASSWORD=TbFpVQzneY2j
      - ENCRYPT_KEY=qwertyuiopas
    networks:
      cloud:
        ipv4_address: 192.168.0.13

  discovery:
    image: cloud/discovery
    restart: always
    ports:
      - "8012:8080"
    environment:
      - ZONE_URI=http://192.168.0.12:8080/eureka/
    networks:
      cloud:
        ipv4_address: 192.168.0.12

  gateway:
    image: cloud/gateway
    restart: always
    ports:
      - "8010:8080"
    environment:
      - ZONE_URI=http://192.168.0.12:8080/eureka/
    networks:
      cloud:
        ipv4_address: 192.168.0.10

  users_database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/users:/var/lib/postgresql/data/application
    networks:
      cloud:
        ipv4_address: 192.168.0.16

  users:
    image: cloud/users
    restart: always
    environment:
      - ZONE_URI=http://192.168.0.12:8080/eureka/
      - CONFIG_URI=http://192.168.0.13:8080
      - ENCRYPT_KEY=qwertyuiopas
      - RABBITMQ_HOST=192.168.0.14
      - RABBITMQ_USERNAME=rabbitbus
      - RABBITMQ_PASSWORD=TbFpVQzneY2j
      - KAFKA_HOST=192.168.0.20
    networks:
      cloud:
        ipv4_address: 192.168.0.15

  organization_database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=organization
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/organization:/var/lib/postgresql/data/application
    networks:
      cloud:
        ipv4_address: 192.168.0.18

  organization:
    image: cloud/organization
    restart: always
    environment:
      - ZONE_URI=http://192.168.0.12:8080/eureka/
      - CONFIG_URI=http://192.168.0.13:8080
      - ENCRYPT_KEY=qwertyuiopas
      - KAFKA_HOST=192.168.0.20
    networks:
      cloud:
        ipv4_address: 192.168.0.17

  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - TOPICS=messages
      - ADVERTISED_HOST=192.168.0.20 # 192.168.0.20 for production
      - ADVERTISED_PORT=9092
    networks:
      cloud:
        ipv4_address: 192.168.0.20

networks:
  cloud:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.0.0/24
