spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/training
    username: lukaszandrzejewski
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG