security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

---
spring:
  profiles: development
  sleuth:
    sampler:
      percentage: 0.1
  zipkin:
    base-url: http://localhost:8003
  cloud:
    stream:
      bindings:
        output:
          destination: messages
          content-type: application/json
server:
  port: 8011
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
signing:
  key: "345345fsdfsf5345"
hystrix:
  shareSecurityContext: true
