server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/training
    username: lukaszandrzejewski
    #password: admin
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
