server:
  port: 8010
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100/platform
    username: platform
    password: platform
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_null
