server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
zuul:
  prefix: /api-v1
  sensitive-headers: Cookie, Set-Cookie

---
spring:
  profiles: development
server:
  port: 8000
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
