spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landrzejewski/spring-cloud-training
          search-paths: configuration-files
        encrypt:
          enabled: false
---
spring:
  profiles: development
server:
  port: 8002