spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landrzejewski/spring-cloud-training
          search-paths: configuration-files

---
spring:
  profiles: development
server:
  port: 8002